### ISSUE TITLE
fixed limit on concurrent batch jobs

### ISSUE THREAD

**Issue by jdries** [eu-cdse/openeo-cdse-infra#9]
allow only 2 concurrent jobs per cdse user

proposal implementation: directly query k8s or else EJR API to get a count of running jobs

**Comment by JeroenVerstraelen** [comment]
Feature has been tested on CDSE.
@jdries Should I also enable it on cdse-prod by setting the CONCURRENT_POD_LIMIT env var there?

**Comment by jdries** [comment]
yes, maybe set it to 10 there
